export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS';
export const SET_EDIT_FALSE = 'SET_EDIT_FALSE';
export const SET_EDIT_RUANGAN = 'SET_EDIT_RUANGAN';
export const SET_EDIT_MATKUL = 'SET_EDIT_MATKUL';
export const SET_EDIT_PRODI = 'SET_EDIT_PRODI';
export const SET_EDIT_KELAS = 'SET_EDIT_KELAS';
export const SET_EDIT_MAHASISWA = 'SET_EDIT_MAHASISWA';
